apiVersion: apps/v1
kind: Deployment
metadata:
  name: collage-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: your-app-container
        image: fahman16/collage:latest
        ports:
          - containerPort: 3000
        env:
         - name: MONGODB_URI
           value: "mongodb://docker:27017/Fahman"
      - name: docker
        image: mongo:latest
        ports:
           - containerPort: 27017