version: '3.8'

services:
  king-4:
    image: david-4
    build: .
    ports:
      - '4000:3000'
    environment:
      - MONGO_URI:'mongodb://127.0.0.1:27017/Fahman'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
